services:
  - type: web
    name: bagbot-v2
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.render-final.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DISCORD_TOKEN
        fromSecret: DISCORD_TOKEN
      - key: CLIENT_ID
        fromSecret: DISCORD_CLIENT_ID
      - key: RENDER_EXTERNAL_URL
        fromService:
          type: web
          name: bagbot-v2
          property: host
      - key: MONGODB_USERNAME
        value: douvdouv21
      - key: MONGODB_PASSWORD
        value: bagv2
      - key: MONGODB_CLUSTER_URL
        value: cluster0.yir9dvo.mongodb.net
      - key: DEBUG_BACKUP
        value: "true"
      - key: YTDLP_DISABLE_DOWNLOAD
        value: "false"
      - key: YTDLP_UPDATE
        value: "false"
      - key: YTDLP_URL
        value: https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp
      - key: YTDLP_DIR
        value: /opt/render/project/src/node_modules/@distube/yt-dlp/bin
      - key: YTDLP_FILENAME
        value: yt-dlp
      - key: YTDL_NO_UPDATE
        value: "1"