services:
  - type: web
    name: bagbot-v2
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.render-final.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DISCORD_TOKEN
        fromSecret: DISCORD_TOKEN
      - key: CLIENT_ID
        fromSecret: DISCORD_CLIENT_ID
      - key: TOPGG_TOKEN
        fromSecret: TOPGG_TOKEN
      - key: DBL_TOKEN
        fromSecret: DBL_TOKEN
      - key: DISCORD_BOATS_TOKEN
        fromSecret: DISCORD_BOATS_TOKEN
      - key: DISCORD_BOTS_GG_TOKEN
        fromSecret: DISCORD_BOTS_GG_TOKEN
      - key: RENDER_EXTERNAL_URL
        fromService:
          type: web
          name: bagbot-v2
          property: host
      - key: MONGODB_USERNAME
        value: douvdouv21
      - key: MONGODB_PASSWORD
        value: bagv2
      - key: MONGODB_CLUSTER_URL
        value: cluster0.yir9dvo.mongodb.net
      - key: DEBUG_BACKUP
        value: "true"
      - key: YTDLP_DISABLE_DOWNLOAD
        value: "false"
      - key: YTDLP_UPDATE
        value: "false"
      - key: YTDLP_URL
        value: https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp
      - key: YTDLP_DIR
        value: /opt/render/project/src/node_modules/@distube/yt-dlp/bin
      - key: YTDLP_FILENAME
        value: yt-dlp
      - key: YTDL_NO_UPDATE
        value: "1"
      - key: YOUTUBE_COOKIES_B64
        fromSecret: YOUTUBE_COOKIES_B64
      - key: YOUTUBE_COOKIES
        fromSecret: YOUTUBE_COOKIES
      - key: YT_COOKIES_FILE
        value: /opt/render/project/src/cookies.txt
      - key: PIPED_TIMEOUT
        value: "15000"
      - key: PIPED_REGION
        value: FR
      - key: PIPED_BASE_URL
        value: https://piped.video
      - key: LAVALINK_HOST
        value: lava-v4.ajieblogs.eu.org
      - key: LAVALINK_PORT
        value: "443"
      - key: LAVALINK_PASSWORD
        value: https://dsc.gg/ajidevserver
      - key: LAVALINK_SECURE
        value: "true"