services:
  - type: web
    name: bagbot-v2
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.render-final.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_USERNAME
        value: YOUR_MONGODB_USERNAME
      - key: MONGODB_PASSWORD
        value: YOUR_MONGODB_PASSWORD  
      - key: MONGODB_CLUSTER_URL
        value: YOUR_CLUSTER_URL