services:
  - type: web
    name: bagbot-v2
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.render-final.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: RENDER_EXTERNAL_URL
        fromService:
          type: web
          name: bagbot-v2
          property: host
      - key: MONGODB_USERNAME
        value: douvdouv21
      - key: MONGODB_PASSWORD
        value: bagv2
      - key: MONGODB_CLUSTER_URL
        value: cluster0.yir9dvo.mongodb.net
      - key: DEBUG_BACKUP
        value: "true"
      - key: YTDLP_DISABLE_DOWNLOAD
        value: "true"
      - key: YTDLP_UPDATE
        value: "false"