# -*- coding: utf-8 -*-
"""
Listes de prompts pour le jeu Action ou Vérité en français.
Contient 100 actions et 100 vérités.
"""

ACTIONS = [
    "Envoie un GIF qui te représente aujourd'hui.",
    "Écris ton prochain message sans utiliser la lettre 'e'.",
    "Complimente la dernière personne qui a écrit ici.",
    "Partage une photo de ton bureau (ou décris-le en 3 mots).",
    "Mets une réaction sur 5 messages au hasard.",
    "Parle uniquement avec des emojis pendant 3 messages.",
    "Change ton surnom sur le serveur pour 'Je suis génial' pendant 10 minutes.",
    "Compose un haïku sur le thème du serveur.",
    "Raconte une blague nulle.",
    "Envoie la dernière musique que tu as écoutée.",
    "Fais un acrostiche avec ton pseudo.",
    "Écris un message en MAJUSCULES seulement.",
    "Utilise un mème pour répondre au message juste au-dessus.",
    "Écris ton prochain message à l'envers.",
    "Fais deviner un film en 3 emojis.",
    "Partage un fun fact que tu connais.",
    "Écris comme un pirate pendant 2 messages.",
    "Envoie un selfie de tes chaussettes ou décris-les.",
    "Poste un message sans utiliser de voyelles (remplace par des '_').",
    "Ping un bot et dis-lui bonjour.",
    "Fais 3 compliments à 3 personnes différentes.",
    "Raconte une mini-histoire en 4 phrases.",
    "Mets un sondage rapide (2 options) sur n'importe quoi.",
    "Envoie l'emoji que tu utilises le plus et explique pourquoi.",
    "Parodie un slogan célèbre avec le thème du serveur.",
    "Fais une devinette et donne la réponse 5 messages plus tard.",
    "Change ta photo de profil pour un animal pendant 10 minutes.",
    "Écris un pangramme contenant toutes les lettres (ou essaie).",
    "Décris ton humeur avec 3 emojis uniquement.",
    "Partage une capture d'écran de ton fond d'écran (ou décris-le).",
    "Réponds au prochain message comme si tu étais un robot.",
    "Réagis avec l'emoji '👍' à 10 messages.",
    "Donne un conseil de productivité.",
    "Envoie une image libre de droit que tu aimes.",
    "Cherche un GIF de chat et poste-le.",
    "Fais une liste de 5 choses qui te motivent.",
    "Écris une phrase où chaque mot commence par la même lettre.",
    "Partage une app que tu recommandes.",
    "Écris ton prochain message sans utiliser la lettre 'a'.",
    "Demande au hasard 'Action ou Vérité ?' à quelqu'un dans le chat.",
    "Dis 'bonjour' dans 5 langues différentes.",
    "Écris un message comme si tu étais un commentateur sportif.",
    "Utilise un spoiler ||comme ça|| dans un message pertinent.",
    "Envoie un message avec un palindrome.",
    "Raconte un souvenir drôle d'école (PG).",
    "Partage ton meilleur raccourci clavier.",
    "Écris une mini-recette en 5 étapes.",
    "Réécris la dernière phrase du chat au style Shakespeare.",
    "Compose un slogan pour le serveur.",
    "Écris un message sans ponctuation",
    "Écris un poème de 4 vers qui rime.",
    "Partage une photo d'un objet rouge autour de toi (ou décris-le).",
    "Envoie un GIF 'fail' et explique.",
    "Change ton statut en 'Action/Vérité en cours' pendant 10 minutes.",
    "Écris comme si tu étais le narrateur d'un documentaire.",
    "Fais deviner ton plat préféré en 3 indices.",
    "Réponds au prochain message avec une rime.",
    "Demande à quelqu'un de choisir un avatar pour toi.",
    "Écris ton prochain message en utilisant uniquement des mots de trois lettres (ou moins).",
    "Ajoute une réaction différente à tes 5 derniers messages.",
    "Décris le serveur comme s'il était un film.",
    "Partage une citation inspirante.",
    "Dessine un emoji avec des caractères (ASCII art simple).",
    "Mets en avant un channel que tu aimes et dis pourquoi.",
    "Envoie un message où chaque mot finit par 'ou'.",
    "Écris un message sans utiliser les lettres 'n', 's', 't'.",
    "Recrée un emoji avec des mots (ex: ':D' -> 'grand sourire').",
    "Envoie un sticker ou un custom emoji drôle.",
    "Raconte une petite victoire récente.",
    "Propose un mini-défi au groupe.",
    "Écris une phrase où chaque mot est plus long que le précédent.",
    "Parle comme Yoda pendant 2 messages.",
    "Poste un 'avant/après' (texte) de ta journée.",
    "Partage un raccourci ou macro que tu utilises.",
    "Écris un faux titre d'article clickbait sur le serveur.",
    "Décris ton poste de travail en trois adjectifs.",
    "Envoie un son ou musique libre de droit qui te plaît.",
    "Écris une micro-fiction en 280 caractères.",
    "Envoie un 'would you rather' avec 2 options.",
    "Dis quelque chose de gentil à la 5e personne au-dessus de toi.",
    "Explique ton pseudo en une phrase.",
    "Partage un fond d'écran minimaliste (ou lien).",
    "Raconte une fois où tu as beaucoup ri en ligne.",
    "Écris une liste de souhaits tech.",
    "Fais une promesse drôle au serveur.",
    "Propose un nouveau rôle amusant pour le serveur.",
    "Donne 3 idées d'événements Discord.",
    "Écris un message avec uniquement des mots qui riment.",
    "Décris ton café/thé idéal.",
    "Partage un raccourci Discord que tout le monde devrait connaître.",
    "Envoie un GIF 'motivation'.",
    "Écris un message en morse pour un mot simple.",
    "Donne 3 objectifs pour cette semaine.",
    "Partage une playlist publique.",
    "Donne un défi de réaction (ex: 5 👍 en 1 min).",
    "Écris ton prochain message en alternant MAJ/min.",
    "Envoie un message codé avec une clé simple (explique).",
    "Propose un 'thread' sur un sujet cool.",
    "Écris comme si tu étais un NPC de jeu vidéo.",
    "Écris un merci collectif au serveur."
]

VERITES = [
    "Quel est ton jeu vidéo préféré du moment et pourquoi ?",
    "Quelle fonctionnalité Discord utilises-tu le plus ?",
    "Quel est le dernier film/série que tu as regardé ?",
    "Quel pseudo aurais-tu si tu devais en changer ?",
    "Quel est ton pire défaut 'en ligne' ?",
    "Quel est ton meilleur souvenir sur ce serveur ?",
    "As-tu déjà supprimé un message et regretté ?",
    "Quel emoji utilises-tu le plus et pourquoi ?",
    "Quel est ton canal préféré ici ?",
    "À quoi ressemble ta matinée idéale ?",
    "Quel est le projet dont tu es le plus fier ?",
    "Quelle est ta plus grande peur tech (panne, perte de données...) ?",
    "Quel est ton snack favori quand tu es sur Discord ?",
    "Quel est ton talent caché (même petit) ?",
    "Quelle est la notification qui t'agace le plus ?",
    "Quelle langue aimerais-tu parler couramment ?",
    "Quel est ton outil/app préféré ?",
    "Plutôt café, thé, ou eau ? Pourquoi ?",
    "Quelle habitude aimerais-tu prendre cette année ?",
    "Quel est le plus gros fou rire que tu aies eu récemment ?",
    "Quel est ton meilleur conseil de productivité ?",
    "Quand as-tu rejoint ce serveur pour la première fois ?",
    "Quel est ton animal préféré ?",
    "Quelle est ta musique 'honteuse' que tu adores ?",
    "Quel est le meilleur conseil qu'on t'ait donné ?",
    "As-tu déjà rencontré quelqu'un de ce serveur IRL ?",
    "Quel est ton emoji perso préféré (custom) ?",
    "Si tu pouvais créer un salon, quel serait son thème ?",
    "Quel est ton mème préféré de tous les temps ?",
    "Quelle est la commande/bot que tu trouves la plus utile ?",
    "Quel est ton rituel avant de te coucher ?",
    "Quel est l'appareil dont tu ne pourrais pas te passer ?",
    "Quelle est ta plus grande source d'inspiration ?",
    "Quel est ton loisir qui surprendrait les autres ?",
    "Sur une échelle 1-10, à quel point es-tu organisé ?",
    "Quelle est la dernière chose que tu as apprise en ligne ?",
    "Quelle est la fonctionnalité Discord que tu aimerais voir exister ?",
    "Quel est ton meilleur achat à moins de 20€ ?",
    "Quel est le message le plus long que tu aies jamais écrit ici ?",
    "Quelle est ta plus grande 'green flag' chez quelqu'un ?",
    "Quelle est la ville que tu rêves de visiter ?",
    "À quel jeu de société es-tu imbattable ?",
    "Quel est ton superpouvoir IRL ?",
    "Quelle est la dernière bonne action que tu as faite ?",
    "Quelle compétence veux-tu apprendre prochainement ?",
    "Quel est ton avatar préféré que tu as utilisé ?",
    "Quelle est ta saison préférée et pourquoi ?",
    "Quel est ton guilty pleasure sur internet ?",
    "Quel est le meilleur moment de ta journée ?",
    "Qu'est-ce qui te fait couper les notifs ?",
    "Quel est ton langage de programmation préféré (si applicable) ?",
    "Quel est le canal où tu parles le moins ? Pourquoi ?",
    "Quelle est la fonctionnalité mobile/desktop que tu préfères ?",
    "Quel est ton plat réconfortant ?",
    "Quelle application utilises-tu trop ?",
    "Quel est ton rêve d'enfant ?",
    "Quel est le message le plus drôle que tu as lu ici ?",
    "Qu'est-ce qui t'énerve instantanément ?",
    "Quel est ton premier jeu dont tu te souviens ?",
    "Qui t'a invité sur ce serveur ?",
    "Quel est un trait de caractère que tu admires ?",
    "Quel est le meilleur emoji pour te décrire ?",
    "Qu'est-ce qui te motive le plus ?",
    "Quelle est ta plus grande fierté cette semaine ?",
    "Quelle est ta pire habitude numérique ?",
    "Comment gères-tu le stress ?",
    "Quel est le dernier cadeau que tu as offert ?",
    "Quelle est ta série que tu recommandes à tout le monde ?",
    "Quelle appli devrais-tu supprimer, mais tu ne peux pas ?",
    "Quelle est ta photo préférée dans ta galerie ?",
    "Quel est ton objectif principal cette année ?",
    "Que changerais-tu sur ce serveur ?",
    "Quel est le dernier apprentissage que tu as partagé ici ?",
    "Qu'est-ce qui te rend unique ici ?",
    "Quelle est la chose la plus courageuse que tu aies faite ?",
    "Quels sont tes trois emojis préférés ?",
    "Quel est ton style de musique préféré ?",
    "Quel est ton meilleur souvenir d'école (PG) ?",
    "Quel est un projet perso que tu veux lancer ?",
    "Qu'est-ce qui te détend le plus ?",
    "Quel est le canal où tu voudrais plus d'activité ?",
    "Quelle est ta relation aux jeux compétitifs ?",
    "Quel est ton top 3 des bots utiles ?",
    "De quoi es-tu le plus reconnaissant aujourd'hui ?",
    "Qu'as-tu appris de quelqu'un ici ?",
    "Quel est un rêve que tu poursuis encore ?",
    "Quel est le dernier bug qui t'a fait rager ?",
    "Quel est ton setup (résume en 3 objets) ?",
    "Quel est ton meilleur conseil 'vie en ligne' ?",
    "Quel est un sujet sur lequel tu pourrais parler des heures ?",
    "Quel est le meilleur compliment que tu aies reçu ?",
    "Quelle est la prochaine compétence que tu veux améliorer ?",
    "Quel est ton lieu préféré pour te concentrer ?",
    "Quel est ton meilleur moment sur Discord ?",
    "Quelle est la chose la plus surprenante que tu aies apprise en ligne ?",
    "Quel serait ton surnom si le groupe votait ?",
    "Quel est ton objectif de bien-être du moment ?",
    "Quel est un échec dont tu es fier ?",
    "Quel est ton rituel du matin ?",
    "Quelle est la chose qui te fait rester sur ce serveur ?"
]