const BASE_ACTIONS = [
  'Fais 10 pompes en caméra vocale (si possible) !',
  'Envoie un GIF qui décrit ton humeur du moment.',
  'Écris un message avec uniquement des emojis pendant 5 minutes.',
  "Change ton pseudo pour quelque chose de drôle pendant 10 minutes.",
  "Partage une musique que tu écoutes souvent en ce moment.",
  "Fais un compliment sincère à quelqu'un dans le salon.",
  "Envoie une photo d'un objet rouge autour de toi (si possible).",
  "Écris un pangramme (une phrase avec toutes les lettres) en français.",
  "Raconte une blague (même nulle).",
  "Utilise un filtre vocal (si possible) pour dire 'Bonjour le monde !'.",
  "Change ton statut en 'Action/Vérité en cours' pendant 10 minutes.",
  "Épelle ton prénom à l'envers.",
  "Raconte un souvenir d'enfance en une phrase.",
  "Trouve un mème et envoie-le ici.",
  "Partage un conseil de productivité que tu utilises.",
  "Décris ton dernier repas en trois mots.",
  "Envoie une photo/emoji de ton animal préféré.",
  "Donne un défi à la personne suivante (gentil).",
  "Écris un haïku (5/7/5) sur Discord.",
  "Envoie un message en MAJUSCULES uniquement pendant 2 messages.",
];

const BASE_TRUTHS = [
  'Quel est ton film préféré de tous les temps ?',
  'Quel est ton plus grand rêve en ce moment ?',
  'Quel talent aimerais-tu avoir ?',
  "Quel est le dernier livre (ou article) que tu as lu et aimé ?",
  "Quel est le plat que tu pourrais manger tous les jours ?",
  "Qu'est-ce qui te fait le plus rire ?",
  "Quel est ton meilleur souvenir récent ?",
  "Quelle est une habitude dont tu es fier/fière ?",
  "Quel est ton jeu vidéo préféré et pourquoi ?",
  "Si tu pouvais voyager maintenant, où irais-tu ?",
  "Quel est ton emoji le plus utilisé ?",
  "De quoi es-tu reconnaissant(e) aujourd'hui ?",
  "Quelle est la chose la plus spontanée que tu aies faite ?",
  "Quel est un objectif pour ce mois-ci ?",
  "Thé ou café ? Pourquoi ?",
  "Matin ou soir ?",
  "As-tu un hobby caché ? Lequel ?",
  "Plutôt mer ou montagne ?",
  "Quel est ton meilleur conseil 'lifehack' ?",
  "Quelle musique te motive instantanément ?",
];

module.exports = { BASE_ACTIONS, BASE_TRUTHS };